services:
  # JOSM
  josm:
    container_name: josm
    build:
      context: ./josm
    environment:
      - VNC_RESOLUTION=1920x1080
    ports:
      - "6901:6901" # noVNC
      - "5901:5901" # VNC
    depends_on:
      - web

  # OPENSTREETMAP WEB API + WEBSITE
  web:
    build:
      context: ./openstreetmap-website/src
    environment:
      PIDFILE: /tmp/pids/server.pid
    volumes:
      - ./openstreetmap-website/src:/app
      - ./openstreetmap-website/config:/app/host/config
      - ./openstreetmap-website/db:/app/host/db
      - ./openstreetmap-website/docker:/app/host/docker
      - /app/node_modules/
      - web-tmp:/app/tmp
      - web-storage:/app/storage
    tmpfs:
      /tmp/pids/
    ports:
      - "3000:3000"
    entrypoint:
      - /bin/sh
      - -lc
      - |
        apt-get update \
        && apt-get install -y --no-install-recommends dos2unix \
        && rm -rf /var/lib/apt/lists/* \
        && dos2unix /app/host/docker/entrypoint.sh \
        && exec /app/host/docker/entrypoint.sh
    depends_on:
      - db

  db:
    build:
      context: ./openstreetmap-website/src
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: openstreetmap
    volumes:
      - web-db-data:/var/lib/postgresql/data

  # OPENSTREETMAP API GATEWAY
  openstreetmap-api-gateway:
    build:
      context: ./openstreetmap-api-gateway
      dockerfile: docker/Dockerfile
    container_name: openstreetmap-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - openstreetmap-quality-framework-db
    environment:
      OSM_API_URL: http://web:3000
      OSM_QUALITY_FRAMEWORK_URL: http://openstreetmap-quality-framework:8080
      OSM_NOTIFICATION_SERVICE_URL: http://openstreetmap-notification-service:8080
    volumes:
      - ./docker/data/pbf/data.osm.pbf:/app/import/data.osm.pbf:ro

  # OPENSTREETMAP QUALITY FRAMEWORK
  openstreetmap-quality-framework-db:
    image: postgis/postgis:17-3.5
    container_name: openstreetmap-quality-framework-db
    command: ["postgres", "-c", "max_connections=300"]
    environment:
      POSTGRES_DB: osm_quality_framework
      POSTGRES_USER: osm_quality_framework_user
      POSTGRES_PASSWORD: osm_quality_framework_pass
    ports:
      - "54322:5432"
    volumes:
      - openstreetmap-quality-framework-db-data:/var/lib/postgresql/data

  openstreetmap-quality-framework:
    build:
      context: ./openstreetmap-quality-framework
      dockerfile: docker/Dockerfile
      args:
        OSM2PGSQL_REPO_URL: https://github.com/osm2pgsql-dev/osm2pgsql.git
        OSM2PGSQL_REPO_BRANCH: master
        OSMOSIS_REPO_TAR: https://github.com/openstreetmap/osmosis/releases/download/0.49.2/osmosis-0.49.2.tar
    container_name: openstreetmap-quality-framework
    ports:
      - "8081:8080"
    depends_on:
      - openstreetmap-quality-framework-db
    environment:
      OSM_API_URL: http://web:3000
      OSM_QUALITY_FRAMEWORK_DATABASE: osm_quality_framework
      OSM_QUALITY_FRAMEWORK_DATABASE_HOST: openstreetmap-quality-framework-db
      OSM_QUALITY_FRAMEWORK_DATABASE_PORT: 5432
      OSM_QUALITY_FRAMEWORK_DATABASE_USERNAME: osm_quality_framework_user
      OSM_QUALITY_FRAMEWORK_DATABASE_PASSWORD: osm_quality_framework_pass
    volumes:
      - ./openstreetmap-quality-framework/docker/data/pbf/data.osm.pbf:/app/import/data.osm.pbf:ro

  # OPENSTREETMAP NOTIFICATION SERVICE
  openstreetmap-notification-service:
    build:
      context: ./openstreetmap-notification-service
      dockerfile: docker/Dockerfile
    container_name: openstreetmap-notification-service
    ports:
      - "8082:8080"
    depends_on:
      - openstreetmap-quality-framework-db
    environment:
      OSM_API_URL: http://web:3000
      OSM_NOTIFICATION_SERVICE_DATABASE: osm_quality_framework
      OSM_NOTIFICATION_SERVICE_DATABASE_HOST: openstreetmap-quality-framework-db
      OSM_NOTIFICATION_SERVICE_DATABASE_PORT: 5432
      OSM_NOTIFICATION_SERVICE_DATABASE_USERNAME: osm_quality_framework_user
      OSM_NOTIFICATION_SERVICE_DATABASE_PASSWORD: osm_quality_framework_pass

volumes:
  web-tmp:
  web-storage:
  web-db-data:
  openstreetmap-quality-framework-db-data: