version: "3.8"

services:
  josm:
    container_name: josm
    build:
      context: ./josm
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    shm_size: "2g"
