version: "3.8"

services:
  josm:
    container_name: josm
    build:
      context: ./josm
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./josm:/app
    network_mode: "host"
    shm_size: "2g"
    depends_on:
      - web

  web:
    build:
      context: ./openstreetmap-website/src
    environment:
      PIDFILE: /tmp/pids/server.pid
    volumes:
      - ./openstreetmap-website/src:/app
      - ./openstreetmap-website/config:/app/host/config
      - ./openstreetmap-website/db:/app/host/db
      - ./openstreetmap-website/docker:/app/host/docker
      - /app/node_modules/
      - web-tmp:/app/tmp
      - web-storage:/app/storage
    tmpfs:
      /tmp/pids/
    ports:
      - "3000:3000"
    entrypoint: /app/host/docker/entrypoint.sh
    depends_on:
      - db

  db:
    build:
      context: ./openstreetmap-website/src
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: openstreetmap_test_environment
    volumes:
      - db-data:/var/lib/postgresql/data

  openstreetmap-schema:
    build:
      context: ./openstreetmap-schema
    volumes:
      - ./openstreetmap-schema:/app
      - ./openstreetmap-schema/docker:/app/host/docker
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 54321
      DATABASE: openstreetmap_test_environment
      OPENSTREETMAP_SCHEMA_DB_USER: openstreetmap_schema_owner
      OPENSTREETMAP_SCHEMA_DB_PASSWORD: password
    ports:
      - "8081:8080"
    entrypoint: /app/host/docker/entrypoint.sh
    depends_on:
      - db

volumes:
  web-tmp:
  web-storage:
  db-data:
